### PR TITLE
Add new version file to track package version. Include in setup.py.

### PR DESCRIPTION
**Pull request by killerbat00**
Resolves issue #20

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
Thank you so much for your contribution! I wasn't aware of handling versions like this. So the module needs to be executed so the version module is too, and then you can also access the `__version__` variable from the module? Why aren't we just using version.__version__ in this context? Thank you so very much for your support! Merged to master. Will close once I get your response and I fully understand the nature of your commit. Thanks, again!

**Comment by lillian-lemmer** [comment]
OH I understand, because if you just imported the version from the module it'd try to fetch all the other modules in the library and hypatia wouldn't be installed yet! Coolio, thanks!

**Comment by killerbat00** [comment]
Yep, exactly.
You could also consider doing this with the other __* variables (e.g. __author__, __credits__, etc). Place them into a single file that you reference from the package init (and you can use them similarly in the setup.py file) This way, they exist in one place in the package which is pretty DRYish. Not strictly necessary or remotely a functional problem, though.

**Comment by lillian-lemmer** [comment]
Nice to know, thanks!

**Pull request merged**
