### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by bsdjunk**
Beer free beer is good

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
The suggested license is not sufficient for preventing people from suing me for damages. I try to stick to well established and well known licenses. Anything else seems to scare people away, plus you have the benefit of it having been through legal rigor.

**Comment by ejmr** [comment]
> The suggested license is not sufficient for preventing people from suing me for damages. I try to stick to well established and well known licenses.

For what my own input is worth, I have seen the MIT License and the GNU General Public License used for technology in the game industry, and practically no other free/libre software licenses such as a Beerware one for exactly the reason you give: it is *vital* to be clear and unambiguous about such things as warranty and liability.

**Comment by lillian-lemmer** [comment]
I fully agree with @ejmr. Closed.

**Comment by lillian-lemmer** [comment]
I appreciate your contribution, @bsdjunk, I really wish we could use that license, "believe, you, me."

**Comment by bsdjunk** [comment]
A lot of code created by phk@ has used this license, it is simple. If you are worried about getting sued then you're doing it wrong.

**Comment by ejmr** [comment]
>  If you are worried about getting sued then you're doing it wrong.

I literally laughed out loud.  Thanks for bringing a smile to my face today! :)

**Comment by bsdjunk** [comment]
My work here is done I guess.

**Comment by ejmr** [comment]
I realize that probably sounded rude and/or condescending, so I apologize, because that wasn't my intent.  Personally I suspect that you and I would share a lot of the same ideals about free software.  But Lillian and I both work on software for use in creating commercial games in the United States, and in that specific context---particularly with regard to *where* we are---using a license that does not explicitly exempt us from liability is a serious risk.  For example, if Hypatia did not use such a license then I could use it to build a game for sale, and then when my business goes broke because I made a terrible, piece of crap game then I could turn around and sue Lillian by blaming my own business failures on the quality of her work.  That is---to be blunt---a completely fucking stupid thing for *anyone* to do, but it's the sad reality that we have to deal with given the combination of the kind of software we work on and the country in which we do so.

Anyway, I don't want to keep nagging Lillian with the emails I know she's surely getting for each one of these messages, so this is my last comment on the matter.  I mainly just wanted to apologize if I sounded rude and clarify/explain why that type of license isn't a reasonable choice in this *specific* context.

**Comment by bsdjunk** [comment]
I meant "My work here in done" as I made you laugh.

**Comment by ejmr** [comment]
Ah I know, thanks again :)

**Comment by lillian-lemmer** [comment]
@ejmr, thank you so much for your amazing reply. Careful, I'm coming to just expect greatness from you. ;D I really appreciate your dedication.

@bsdjunk I'm really grateful that you took the time to make this consideration and bring it up for review. It's healthy to have a conversation about these sorta things, make sure we're doing everything for a reason. :) I think @ejmr enumerated the reasons perfectly.

Great work, everyone!

**Comment by ejmr** [comment]
>  Careful, I'm coming to just expect greatness from you.

@lillian-lemmer I would lower those expectations if I were you, heh.

**Comment by lillian-lemmer** [comment]
You're too modest <3

**Comment by bsdjunk** [comment]
If you two are going to sweet talk each other then tell me how to remove myself from these emails being sent to me.

**Comment by bsdjunk** [comment]
Ok done, you may continue now.

**Comment by ejmr** [comment]
Another legitimate laugh out loud moment.  Although I understand his point, heh.

**Pull request closed without merging**
