### PR TITLE
[Test] Add a shell script to install `py.test`

### PR DESCRIPTION
**Pull request by ejmr**
This patch adds a shell script to the `tests/` directory which will
install `py.test` on the developer's system, since that is the tool
used for Hypatia's test suite.  The rationale for putting this into a
separate script and not the existing installation scripts is that
pytest is *not* required for running Hypatia, only for developing it.
Therefore we do not want to install unnecessary dependencies for users
who are installing Hypatia with no intention of doing any serious
amount of development.

The installation script tries to install the Python 3 version of
pytest by testing for the existence of `pip3`.  The justification here
is that if `pip3` exists then it is very likely the developer prefers
to work on Hypatia using Python 3.  The script will fallback to the
Python 2.7 version of `pip` if `pip3` is not available.

The script relies on the use of redirecting output to `/dev/null` as
part of testing whether or not pytest installed successfully, which is
an aspect of the script that may break on Windows systems.  I do not
remember off the top of my head if Windows ports of shells like GNU
Bash handle `/dev/null` appropriately for that operating system.

Signed-off-by: Eric James Michael Ritz <ejmr@plutono.com>

GitHub-Issue: #42
See-Also: http://pytest.org/latest/

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
Thank you very much, ejmr! I really appreciate your continued support!

The tests I run (see: test.sh) require more than py.test. Thus, I think it'd be good to have a general `requirements/testing.txt` for `pip install --user requirements/testing.txt`, especially since all the requirements can be installed via pip.

Nonetheless, I'll make sure to actually *look* at your commits later. :) I pretty much just woke up--what a nice thing to wake up to, by the by. :) Thanks, again!

**Comment by lillian-lemmer** [comment]
However, great script! Install script are always welcome. Just wanted to tip you off to how I've been handling requirements now. I should go back and update my install scripts to no pip install by name e.g., `pip install pytest`, but to install the requirement files in `requirements`, e.g., `base.txt.`.

**Comment by lillian-lemmer** [comment]
Wow, yeah, super great job on the install script! I'll be merging this and then modifying all install scripts (including this one) to use the requirements files. :+1: 

Thank you so much! I'll get back to you later. Great shell scripting though, ejmr. :)

**Comment by ejmr** [comment]
> The tests I run (see: test.sh) require more than py.test. Thus, I think it'd be good to have a general requirements/testing.txt for pip install --user requirements/testing.txt, especially since all the requirements can be installed via pip.

Very good idea IMO.  That would be a nice improvement over my script.

**Comment by lillian-lemmer** [comment]
Hopes this works for you. If it doesn't, just open a new issue about it, please.

`pip install -r requirements/testing.txt`

https://github.com/lillian-lemmer/hypatia/blob/develop/requirements/testing.txt

**Comment by ejmr** [comment]
Sorry for the late reply, but `pip install -r requirements/testing.txt` worked just fine.

**Comment by lillian-lemmer** [comment]
No problem, glad that got figured out. :)

**Pull request closed without merging**
